-- 1. Ensure messages table exists with correct schema
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    sender_id UUID NOT NULL REFERENCES auth.users(id),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable RLS on the table
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Users can view messages for connections they are part of
-- Note: This assumes 'connections' table has sender_id and receiver_id
DROP POLICY IF EXISTS "Users can view messages for their connections" ON public.messages;
CREATE POLICY "Users can view messages for their connections" 
ON public.messages FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.connections c
    WHERE c.id = messages.connection_id
    AND (c.sender_id = auth.uid() OR c.receiver_id = auth.uid())
  )
);

-- 4. Policy: Users can insert messages if they are part of the connection
DROP POLICY IF EXISTS "Users can insert messages to their connections" ON public.messages;
CREATE POLICY "Users can insert messages to their connections"
ON public.messages FOR INSERT
WITH CHECK (
  auth.uid() = sender_id AND
  EXISTS (
    SELECT 1 FROM public.connections c
    WHERE c.id = connection_id
    AND (c.sender_id = auth.uid() OR c.receiver_id = auth.uid())
  )
);

-- 5. IMPORTANT: Enable Realtime for the messages table
-- This allows the .stream() in Flutter to actually receive updates
ALTER PUBLICATION supabase_realtime ADD TABLE messages;
-- (If publication doesn't exist or table is already there, you might need to adjust this in Supabase UI -> Database -> Replication)
